#!/usr/bin/env python
#-*- coding:utf-8 -*-

import sys
import base64
from optparse import OptionParser
from image2py import Converter
from image2py.templates import BasicTemplate, QtTemplate, PySideTemplate, PyQtTemplate
VERSION = "0.1.0"

template_lookup = {
    'basic': BasicTemplate,
    'qt': QtTemplate,
    'pyside': PySideTemplate,
    'pyqt': PyQtTemplate
}

def main():
    parser = OptionParser(usage="usage: %prog [options] file1 file2 ...")
    parser.version = VERSION
    parser.add_option('-f', '--file',
                      dest="filename",
                      metavar="FILE",
                      help=("File to which to save. It will be loaded if "
                            "file exists and contains result of image2py"),
                      default=None)
    parser.add_option("-t", "--template",
                      action="store",
                      dest="template",
                      default=None,
                      help="template of output (qt, pyqt, pyside)")
    (options, args) = parser.parse_args()
    if len(args) < 1:
        parser.print_help()
        sys.exit(0)
    conv = Converter(options.filename)
    if options.template is not None:
        clear_template = options.template.strip().lower()
        if clear_template in template_lookup.keys():
            conv.set_template(template_lookup[clear_template]())
        else:
            print('Wrong template given - {}'.format(options.template))
            print('Supported templates are: BASIC, QT, PYSIDE, PYQT')
            sys.exit(0)
    for item in args:
        conv.add_file(item)
    try:
        if options.filename is None:
            print(conv.output())
        else:
            conv.save(options.filename)
            print("File has been saved")
    except Exception as e:
        print('Error: {!s}'.format(e))

if __name__ == "__main__":
    main()
